name: citw_analysis
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.4.2
  - matplotlib=3.5.1
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.2.2
  - ipykernel=6.13.0
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - nb_conda_kernels=2.3.1
  - notebook=6.4.11
  - numpy=1.21.5
  - numpy-base=1.21.5
  - scikit-posthocs=0.6.7
  - scipy=1.8.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - sympy=1.10.1
  